version: '3'
services:
    mysql_compose:
        #构建mysql镜像
        image: mysql:${MYSQL_VERSION}
        container_name: mysql
        command: mysqld --user=mysql
          --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
        ports:
          - ${MYSQL_PORT}:3306
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - /etc/hosts:/etc/hosts:ro
          - ${BASE_DIR}/mysql/data:/data/lib/mysql
          - ${BASE_DIR}/mysql/conf/my.cnf:/etc/mysql/my.cnf
          - ${BASE_DIR}/mysql/log/mysqld.log:/var/log/mysqld.log
