version: '3.7'
services:
  sentinel1:
    image: redis
    container_name: redis-sentinel-1
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    restart: always
#    network_mode: "host"
    ports:
      - 36379:26379
    volumes:
      - ${BASE_DIR}/redis-sentinel/conf/sentinel_1.conf:/usr/local/etc/redis/sentinel.conf

  sentinel2:
    image: redis
    container_name: redis-sentinel-2
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    restart: always
    ports:
      - 36380:26379
#    network_mode: "host"
    volumes:
      - ${BASE_DIR}/redis-sentinel/conf/sentinel_2.conf:/usr/local/etc/redis/sentinel.conf

  sentinel3:
    image: redis
    container_name: redis-sentinel-3
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    restart: always
 #   network_mode: "host"
    ports:
      - 36381:26379
    volumes:
      - ${BASE_DIR}/redis-sentinel/conf/sentinel_3.conf:/usr/local/etc/redis/sentinel.conf